
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA COMA FOR ID IGUAL LLAVE_DER LLAVE_IZQ MASMAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOSMENOS NUMERO OPERADOR PARENTESIS_DER PARENTESIS_IZQ PRINT PUNTO PUNTOYCOMA SYSTEM\nprograma : sentencias\n\nsentencias : sentencia sentencias \n            | sentencia\n            | \n\nsentencia : sentencia_for\n            | asignacion PUNTOYCOMA\n            | llamada_funcion PUNTOYCOMA\n\nsentencia_for : FOR PARENTESIS_IZQ asignacion PUNTOYCOMA condicion PUNTOYCOMA incremento PARENTESIS_DER LLAVE_IZQ cuerpo LLAVE_DER\n\nasignacion : ID IGUAL NUMERO\n            | ID IGUAL ID\n\ncondicion : ID MAYORIGUAL NUMERO\n            | ID MENOR NUMERO\n            | ID MAYOR NUMERO\n            | ID MENORIGUAL NUMERO\n            | ID IGUAL NUMERO\n\nincremento : ID MASMAS\n            | ID MENOSMENOS\n            | ID IGUAL ID OPERADOR NUMERO\n            | ID OPERADOR OPERADOR\n\ncuerpo : sentencias\n\nllamada_funcion : SYSTEM PUNTO PRINT PARENTESIS_IZQ parametros PARENTESIS_DER\n\nparametros : CADENA COMA ID\n            | CADENA\n            | ID\n            | NUMERO\n            | \n\nsentencia : NUMERO ID IGUAL NUMERO PUNTOYCOMA\n\nasignacion : NUMERO ID\n          | OPERADOR NUMERO\n          | ID ID\n\nsentencia_for : FOR LLAVE_IZQ asignacion PUNTOYCOMA condicion PUNTOYCOMA incremento LLAVE_DER LLAVE_IZQ cuerpo LLAVE_DER\n\nsentencia_for : FOR PARENTESIS_IZQ asignacion condicion PUNTOYCOMA incremento PARENTESIS_DER LLAVE_IZQ cuerpo LLAVE_DER\n\nllamada_funcion : SYSTEM PUNTO PRINT parametros PARENTESIS_DER\n'
    
_lr_action_items = {'$end':([0,1,2,3,4,12,13,14,40,81,84,85,],[-4,0,-1,-3,-5,-2,-6,-7,-27,-32,-8,-31,]),'NUMERO':([0,3,4,10,13,14,17,18,19,22,28,35,40,43,44,45,46,47,71,75,78,79,81,84,85,],[7,7,-5,20,-6,-7,24,26,26,29,39,39,-27,55,56,57,58,59,7,7,82,7,-32,-8,-31,]),'FOR':([0,3,4,13,14,40,71,75,79,81,84,85,],[9,9,-5,-6,-7,-27,9,9,9,-32,-8,-31,]),'ID':([0,3,4,7,8,13,14,16,17,18,19,20,23,24,25,26,28,30,33,34,35,40,42,51,52,60,67,71,75,79,81,84,85,],[8,8,-5,15,16,-6,-7,-30,23,8,8,-29,-10,-9,32,33,38,32,-28,32,38,-27,54,62,54,54,72,8,8,8,-32,-8,-31,]),'OPERADOR':([0,3,4,13,14,18,19,40,54,68,71,72,75,79,81,84,85,],[10,10,-5,-6,-7,10,10,-27,68,73,10,78,10,10,-32,-8,-31,]),'SYSTEM':([0,3,4,13,14,40,71,75,79,81,84,85,],[11,11,-5,-6,-7,-27,11,11,11,-32,-8,-31,]),'LLAVE_DER':([3,4,12,13,14,40,65,66,69,71,73,75,76,77,79,80,81,82,83,84,85,],[-3,-5,-2,-6,-7,-27,-16,-17,74,-4,-19,-4,81,-20,-4,84,-32,-18,85,-8,-31,]),'PUNTOYCOMA':([5,6,15,16,20,23,24,25,27,29,31,33,41,48,50,55,56,57,58,59,61,],[13,14,-28,-30,-29,-10,-9,30,34,40,42,-28,52,60,-33,-11,-12,-13,-14,-15,-21,]),'IGUAL':([8,15,32,54,],[17,22,47,67,]),'PARENTESIS_IZQ':([9,28,],[18,35,]),'LLAVE_IZQ':([9,64,70,74,],[19,71,75,79,]),'PUNTO':([11,],[21,]),'PRINT':([21,],[28,]),'CADENA':([28,35,],[37,37,]),'PARENTESIS_DER':([28,35,36,37,38,39,49,53,62,63,65,66,73,82,],[-26,-26,50,-23,-24,-25,61,64,-22,70,-16,-17,-19,-18,]),'MAYORIGUAL':([32,],[43,]),'MENOR':([32,],[44,]),'MAYOR':([32,],[45,]),'MENORIGUAL':([32,],[46,]),'COMA':([37,],[51,]),'MASMAS':([54,],[65,]),'MENOSMENOS':([54,],[66,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'sentencias':([0,3,71,75,79,],[2,12,77,77,77,]),'sentencia':([0,3,71,75,79,],[3,3,3,3,3,]),'sentencia_for':([0,3,71,75,79,],[4,4,4,4,4,]),'asignacion':([0,3,18,19,71,75,79,],[5,5,25,27,5,5,5,]),'llamada_funcion':([0,3,71,75,79,],[6,6,6,6,6,]),'condicion':([25,30,34,],[31,41,48,]),'parametros':([28,35,],[36,49,]),'incremento':([42,52,60,],[53,63,69,]),'cuerpo':([71,75,79,],[76,80,83,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> sentencias','programa',1,'p_programa','parser.py',8),
  ('sentencias -> sentencia sentencias','sentencias',2,'p_sentencias','parser.py',14),
  ('sentencias -> sentencia','sentencias',1,'p_sentencias','parser.py',15),
  ('sentencias -> <empty>','sentencias',0,'p_sentencias','parser.py',16),
  ('sentencia -> sentencia_for','sentencia',1,'p_sentencia','parser.py',22),
  ('sentencia -> asignacion PUNTOYCOMA','sentencia',2,'p_sentencia','parser.py',23),
  ('sentencia -> llamada_funcion PUNTOYCOMA','sentencia',2,'p_sentencia','parser.py',24),
  ('sentencia_for -> FOR PARENTESIS_IZQ asignacion PUNTOYCOMA condicion PUNTOYCOMA incremento PARENTESIS_DER LLAVE_IZQ cuerpo LLAVE_DER','sentencia_for',11,'p_sentencia_for','parser.py',30),
  ('asignacion -> ID IGUAL NUMERO','asignacion',3,'p_asignacion','parser.py',36),
  ('asignacion -> ID IGUAL ID','asignacion',3,'p_asignacion','parser.py',37),
  ('condicion -> ID MAYORIGUAL NUMERO','condicion',3,'p_condicion','parser.py',43),
  ('condicion -> ID MENOR NUMERO','condicion',3,'p_condicion','parser.py',44),
  ('condicion -> ID MAYOR NUMERO','condicion',3,'p_condicion','parser.py',45),
  ('condicion -> ID MENORIGUAL NUMERO','condicion',3,'p_condicion','parser.py',46),
  ('condicion -> ID IGUAL NUMERO','condicion',3,'p_condicion','parser.py',47),
  ('incremento -> ID MASMAS','incremento',2,'p_incremento','parser.py',53),
  ('incremento -> ID MENOSMENOS','incremento',2,'p_incremento','parser.py',54),
  ('incremento -> ID IGUAL ID OPERADOR NUMERO','incremento',5,'p_incremento','parser.py',55),
  ('incremento -> ID OPERADOR OPERADOR','incremento',3,'p_incremento','parser.py',56),
  ('cuerpo -> sentencias','cuerpo',1,'p_cuerpo','parser.py',65),
  ('llamada_funcion -> SYSTEM PUNTO PRINT PARENTESIS_IZQ parametros PARENTESIS_DER','llamada_funcion',6,'p_llamada_funcion','parser.py',71),
  ('parametros -> CADENA COMA ID','parametros',3,'p_parametros','parser.py',77),
  ('parametros -> CADENA','parametros',1,'p_parametros','parser.py',78),
  ('parametros -> ID','parametros',1,'p_parametros','parser.py',79),
  ('parametros -> NUMERO','parametros',1,'p_parametros','parser.py',80),
  ('parametros -> <empty>','parametros',0,'p_parametros','parser.py',81),
  ('sentencia -> NUMERO ID IGUAL NUMERO PUNTOYCOMA','sentencia',5,'p_sentencia_error_numero_id','parser.py',92),
  ('asignacion -> NUMERO ID','asignacion',2,'p_asignacion_error','parser.py',99),
  ('asignacion -> OPERADOR NUMERO','asignacion',2,'p_asignacion_error','parser.py',100),
  ('asignacion -> ID ID','asignacion',2,'p_asignacion_error','parser.py',101),
  ('sentencia_for -> FOR LLAVE_IZQ asignacion PUNTOYCOMA condicion PUNTOYCOMA incremento LLAVE_DER LLAVE_IZQ cuerpo LLAVE_DER','sentencia_for',11,'p_for_error_parentesis','parser.py',112),
  ('sentencia_for -> FOR PARENTESIS_IZQ asignacion condicion PUNTOYCOMA incremento PARENTESIS_DER LLAVE_IZQ cuerpo LLAVE_DER','sentencia_for',10,'p_for_error_puntoycoma','parser.py',119),
  ('llamada_funcion -> SYSTEM PUNTO PRINT parametros PARENTESIS_DER','llamada_funcion',5,'p_llamada_error_parentesis','parser.py',126),
]
